name: SDK test

on:
  workflow_dispatch:
  push:

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    # env:
    #   # Configure a constant location for the uv cache
    #   UV_CACHE_DIR: /tmp/.uv-cache
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
          enable-cache: true
          prune-cache: false

    - name: Set up Python
      run: uv python install

    # - name: Restore uv cache
    #   uses: actions/cache@v4
    #   with:
    #       path: /tmp/.uv-cache
    #       key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
    #       restore-keys: |
    #         uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
    #         uv-${{ runner.os }}
      
    - name: Install dependencies
      run: uv sync --locked

      
